//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 175-3d-printer
//  @ File Name : Microstep.h
//  @ Date : 01.01.2002
//  @ Author : 
//
//


#if !defined(_MICROSTEP_H)
#define _MICROSTEP_H
#include <stdint.h>

// определяется количеством разрядов Расширителя порта.
#define MSG_LENGTH  3


#define M1  (1)
#define M2  (1<<1)
#define M3  (1<<2)
#define EN_X    (1<<0)
#define EN_Y    (1<<1)
#define EN_Z    (1<<2)
#define EN_E0   (1<<3)
#define EN_E1   (1<<4)

struct Microstep {
	uint32_t E1:3;
	uint32_t EN:5;
	uint32_t Z:3;
	uint32_t E0:3;
	uint32_t em2:2;
	uint32_t X:3;
	uint32_t Y:3;
	uint32_t em1:2;
    uint32_t em0:8;
};

union uMicrostep {
    struct  Microstep microsteps;
    uint8_t data[4];
};


#endif  //_MICROSTEP_H
